version: '3'

services:
  selenium-hub:
    image: selenium/hub:4.34.0
    container_name: selenium-hub
    ports:
      - "4442-4444:4442-4444"
    networks:
      - grid

  node-chrome:
    image: selenium/node-chrome-debug:4.34.0
    container_name: node-chrome
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5900:5900"
    networks:
      - grid

  node-firefox:
    image: selenium/node-firefox-debug:4.34.0
    container_name: node-firefox
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5901:5900"
    networks:
      - grid

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - grid
    depends_on:
      - selenium-hub
      - node-chrome
      - node-firefox

networks:
  grid:
    driver: bridge

volumes:
  jenkins_home:
